# Upload port
PORT=/dev/ttyUSB0
# Compile and upload target
TARGET=ProMini
# List of github repos required by this sketch
GITHUB_REPOS=adafruit/Adafruit_Neopixel adafruit/Adafruit_Sensor

include ../Arduino.mk
